[pco]
# All times in SECONDS (s)
exposure_time = 0.001   
frame_period  = 0.02
roi_x = 0
roi_y = 0
roi_width = 2048
roi_height = 2048
queue_size = 64
trigger_mode_ = 0;
pixel_rate_ = 0
pixel_format = Mono8