[pco_edge]
; All times in SECONDS (s) PCO.edge
exposure_time = 0.024
frame_period  = 0.025
roi_x = 0
roi_y = 0
; max. roi_width/height 2048
roi_width = 2048
roi_height = 2048
; trigger_mode: 0=FreeRun(auto) 1=Software 2=External | pixel_rate: Sensor readout speed in Hz (higher=faster fps)
trigger_mode_ = 0;
pixel_rate_ = 0
; pixel_format = Mono16 or  Mono8
pixel_format = Mono16