name: Holovibes CI

on:
  pull_request_target:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        pip install conan
        conan install . --build missing --settings compiler.cppstd=20 --settings build_type=Release
    - name: Building the projet
      run: |
        ./dev.py clean build -b Release
    - name: Run Tests
      run: |
        ./dev.py pytest -b Release
